### ISSUE TITLE
Modelagem Estática 

### ISSUE THREAD

**Issue by guivilela7** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#11]
## Definição dos membros 

Conforme definido na reunião do dia [26/04](https://unbarqdsw2023-1.github.io/2023.1_G5_ProjetoRiHappy/#/Atas/ata_26_04_2023), os responsáveis pelo modelo dinâmico são: João Pedro, Josué Teixeira, Lucas Felipe, Luíza Esteves e Maria Abritta. 

## Diretrizes da entrega

Entrega Mínina: 1 Modelo Estático (ESCOPO: Diagrama de Classes; Diagrama de Pacotes; Diagrama de Componentes ou Diagrama de Implantação).

## Tarefas
- [ ] Definir qual artefato será elaborado
- [ ] Estudo individual (comentar materiais de estudo utilizados nessa issue)
- [ ] Reunião do subgrupo para definir as tarefas
- [ ] Entregas parciais do artefato para revisão pelos membros do outro subgrupo de trabalho

**Comment by lucasfs1007** [comment]
Definimos que 3 pessoas vão trabalhar com o diagrama de classes e outras duas pessoas trabalharão com o diagrama de pacotes, com isso iremos modelar no seguinte link: https://lucid.app/lucidchart/4dd6a296-dbea-46b7-8bb7-b515fbc1fb05/edit?viewport_loc=-197%2C-21%2C2922%2C1261%2CHWEp-vi-RSFO&invitationId=inv_32177c76-50f9-40b1-95df-7711173e673f O diagrama de classes

**Comment by zjosuez** [comment]
- [Link](https://aprender3.unb.br/pluginfile.php/2482560/mod_label/intro/Arquitetura%20e%20Desenho%20de%20Software%20-%20Aula%20Modelagem%20UML%20Est%C3%A1tica%20-%20Profa.%20Milene.pdf) referente ao slide do diagrama de classes da professora
- [Link](https://aprender3.unb.br/course/view.php?id=17703#section-3) da seção com todos os conteúdos sobre diagramas de classes no aprender
