### ISSUE TITLE
Padrões de Projeto - GRASP

### ISSUE THREAD

**Issue by guivilela7** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#12]
# Feature

Descrição dos padrões de projeto GRASP utilizados no projeto. A entrega mínima consiste na aplicação de um dos padrões GRASP, dentre:

- [x]  Criador: @nszchagas 
- [x]  Especialista na Informação: @lucasfs1007 
- [x]  Alta Coesão: @luiza-esteves 
- [x]  Baixo Acoplamento: @luiza-esteves 
- [x]  Controlador: @daves22 
- [x]  Polimorfismo
- [x] #54 @MariaAbritta 
- [x]  Fabricação ou Invenção Pura
- [x]  Variações Protegidas: @guivilela7 

## Tarefas

- [ ] Alocar os membros da equipe em estudos sobre um ou mais padrões.
- [ ] Separar material de estudo 
- [ ] Estudar o assunto 
- [ ] Definir quais padrões fazem sentido no escopo do trabalho

**Comment by nszchagas** [comment]
Vou estudar o padrão criador.

**Comment by lucasfs1007** [comment]
Vou estudar o padrão especialista na informação

**Comment by DaviSilva25** [comment]
Vou estudar os padrões **Invenção pura** e **Polimorfismo**

**Comment by luiza-esteves** [comment]
Vou estudar alta coesão e baixo acoplamento

**Comment by daves22** [comment]
Vou estudar o padrão controlador

**Comment by MariaAbritta** [comment]
[Documento de estudo do Padrão GRASP de Indireção](https://docs.google.com/document/d/1sPowz4YF5RSaMrHzEEhw7C9Urt1hPbUR1OOpPaLt0o8/edit?usp=sharing)

**Comment by nszchagas** [comment]
Finalizados os estudos agora partimos para a implementação no projeto.
