### ISSUE TITLE
Reutilização de Software

### ISSUE THREAD

**Issue by guivilela7** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#16]
# Feature

Esta issue tem como objetivo identificar, discutir e levantar soluções acerca da reutilização de software no projeto

## Tarefas

- [ ] Separar material de estudo (Exemplo)
- [ ] Estudar o assunto (Exemplo)
- [ ] Parear e fazer definições (Exemplo)
- [ ] Elaborar artefato (Exemplo)

**Comment by DaviSilva25** [comment]
Eu e o @lucasgabriel-2 conversamos com a professora no dia 21/06 e conseguimos levantar alguns pontos importante a serem trabalhados nessa entrega, basicamente o que ela nos passou foi que devemos tentar enxergar exemplos de reutilização desde a nível de modelagem, projeto, código e bibliotecas e framework. O que for possível ser reutilizado pode entrar no nosso escopo

Vou deixar separado os tópicos abaixo, como um conceito mais geral para podermos nos aprofundar melhor durante a elaboração dos mesmos.

## Tópicos

- [ ] Reutilização à nível de código (Responsável: )
- [ ] Reutilização à nível de requisitos (Responsável: )
- [ ] Reutilização à nível de projeto (Responsável: )
- [ ] Reutilização à nível de bibliotecas e frameworks (Responsável: )

Lembrando que isso é um levantamento inicial e podemos achar mais níveis para serem utilizados.

**Comment by DaviSilva25** [comment]
Criei uma branch chamada "reutilizacao" para uso dos integrantes da issue

**Comment by nszchagas** [comment]
Conforme conversamos na reunião ontem, tenho algumas sugestões de reutilização externa para vocês, caso queiram utilizá-las e quiserem uma ajuda podem falar comigo também. :) 

- Frameworks (Como o [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/))
- Utilização de bibliotecas interessantes ao nosso contexto, como o Jackson ([Jackson Object Mapper](https://www.devmedia.com.br/introducao-ao-jackson-objectmapper/43174))
- Bibliotecas de conexão com o banco de dados, como o Hibernate ([Hibernate com Spring Boot](https://www.baeldung.com/spring-boot-hibernate))
- Versionador de Banco de Dados, com o Flyway (Flyway) ([Database Migrations with Flyway](https://www.baeldung.com/database-migrations-with-flyway))
- Biblioteca RXJS do JavaScript, com padrão [Observer](https://rxjs.dev/guide/observer) implementado (Front).
- Containers de ambiente e deploy com Docker e Docker Compose e orquestração de containers com Docker Swarm ([Docker docs](https://docs.docker.com/))

**Comment by DaviSilva25** [comment]
Após a reunião do dia 21/06, discutimos no telegram sobre a definição dos tópicos para essa entrega, resultando na seguinte separação:
![image](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/79341819/81020f6f-f7ca-4144-941b-f28959bd98e4)
E com os tópicos definidos, alocamos o membros para a realização das tarefas:
![image](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/79341819/00b661a4-bcc2-4b22-82fb-7b7df3b31c58)

**Comment by nszchagas** [comment]
Bom dia pessoal, conforme conversamos depois da aula de hoje, vamos implementar um exemplo de código para a listagem de avaliações, compras e produtos. Criei a branch `codigo` para trabalharmos, e vou inserir nela a estrutura inicial do projeto, inicializado com spring boot.

Para inicializar o projeto utilizei o [Spring Initializr](https://start.spring.io/), com as seguintes configurações: 

![image](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/68018675/da680139-0cf8-4f57-9a64-72a8378719fc)

Já estão inclusas as bibliotecas spring web, para utilização de API REST, e o driver para conexão com o bancco de dados escolhido, postgres. No nosso exemplo não utilizaremos o banco, mas já podemos incluir essa configuração na reutilização de código.

**Comment by nszchagas** [comment]
Em relação ao frontend, parti da premissa que os frameworks de frontend geram os arquivos "index.html, styles.css, main.js" e podemos partir do ponto que já temos esses arquivos para fazer o deploy e demonstração do nosso exemplo de listagem. 

Já criei os arquivos, e utilizei como base os arquivos do projeto que fiz na disciplina de Projeto de Algoritmos em html e js puro, lá eu criei uma função para transformar uma lista em tabela, e acho que podemos reaproveitar o esqueleto da função para exibir a listagem de itens.

[Ex: Arquivo com a conversão do tipo Task em tabela](https://github.com/projeto-de-algoritmos/Greed_ScheduleOrganizer/blob/master/task.js)


Os arquivos do front estão na pasta /front na raiz do projeto, na branch `codigo`.

**Comment by guivilela7** [comment]
Comecei a mexer um pouco no frontend e adicionei um método beeem básico pra criar uma tabela, só pra dar uma ideia.

Dando uma olhada no exemplo que o @nszchagas mandou no comentário anterior, se eu entendi direito o arquivo task.js define a tabela e o tasklist.js que cria a tabela no front em si. Eu to correto? Se não pode me explicar um pouquinho melhor?

**Comment by daves22** [comment]
Eu e o @lucasgabriel-2 pensamos em adicionar as seguintes ferramentas e frameworks (se alguém tiver mais alguma ideia pode ir comentando pra ajudar)
Framework: Spring Boot.
Bibliotecas: RXJS, Hibernate, Jackson.
Ferramentas: Flyway, Docker.

**Comment by guivilela7** [comment]
A gente chegou a comentar do git como ferramenta tbm, acho que pode ser válido o ZenHub que a gente usou no começo também

**Comment by lucasgabriel-2** [comment]
Eu e o @daves22 nos reunimos e demos prosseguimento ao desenvolvimento do artefato de Reutilização de Software e organizamos da seguinte forma, para cada tópico na parte de Reutilização Externa, como pode ser observado a seguir, criticas e sugestões de melhorias são bem vindas.

- Frameworks: JUnit 5, Spring Boot e Hibernate
- Bibliotecas: RXJS no contexto de Observador, React JS e Jackson ObjectMapper
- Banco de Dados: PostgreSQL
- Ferramentas:  GitHub, ZenHub, FlyWay e Docker
