### ISSUE TITLE
Diagrama de causa e efeito

### ISSUE THREAD

**Issue by lucasfs1007** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#3]
- [x] Estudar o diagrama de causa e efeito
- [x] Criar o modelo do diagrama
- [x] Realizar brainstorm
- [x] Revisar o diagrama com o grupo/professora
- [x] Entrega do diagrama

**Comment by nszchagas** [comment]
Separei esse material para estudo: https://asq.org/quality-resources/fishbone

**Comment by zjosuez** [comment]
O video recomendado pela professora também é muito bom: [Link](https://www.youtube.com/watch?v=U-0qzmFqH-0)

**Comment by nszchagas** [comment]
Obrigado pela recomendação @zjosuez, havia me esquecido do vídeo. 

## 1º passo: Definição do efeito

Após ver o vídeo e partir dos elementos elencados pelo @lucasfs1007 no Miro, seguindo a metodologia mostrada, cheguei a um efeito que podemos analisar:

- Falta de confiabilidade do comprador nos produtos vendidos 

## 3º Causas potenciais 

Esse efeito pode vir por causas como:

- Avaliações errôneas: avaliações negativas de pessoas que não compraram o produto podem afetar na confiabilidade da loja.
- Falta de avaliações: falta de avaliações sobre o produto.
    - Subcausa: interface pouco intuitiva: quão complexo para o usuário é encontrar o fluxo de avaliação? E quão burocrático é esse processo? Ele pode determinar quais avaliações deseja ver, filtrando por franquia ou avaliações com imagens, por exemplo? 
    - Subcausa: falta de motivação do comprador em avaliar: por que o usuário preencheria a avaliação? Existe alguma política de cupons ou cashback, por exemplo, para avaliações relevantes (com muitos likes)?

- Avaliações pouco construtivas/detalhadas:  avaliações muito gerais, como "bom", ou sem detalhes como franquia da compra e data, não são tão fiéis à realidade
- Avaliações de pessoas que não compraram o produto: como validar que a avaliação está relacionada a uma compra, sem tornar a avaliação burocrática (pedindo um login, por exemplo)?
- Falta de respostas da loja nas avaliações: seria uma possibilidade terceirizar o serviço de avaliações? Sugerir ao usuário uma troca ou devolução em caso de avaliação negativa, antes da sua publicação? 

## 2º Escolher categorias 

Achei um pouco mais fácil pensar nas causas antes de categoriar, mas ainda estou com dificuldades nessa parte. A partir das categorias que o Luquinhas listou e dos problemas acima, penso que seriam importantes: 

- Processo/fluxo de avaliação no sistema
- Interação Humano Computador (IHC)
- Motivação 

O que vocês acham @zjosuez  e @lucasfs1007? Já deixei detalhado aqui meu fluxo de pensamento para facilitar a documentação no artefato depois kkk :)

**Comment by lucasfs1007** [comment]
Maravilha, já temos insumos suficientes para fazermos o "Brainstorm". Com isso encaminharmos esse  diagrama.

**Comment by zjosuez** [comment]
Vamos fazer o brainstorm durante a aula ou vamos marcar um horário?

**Comment by nszchagas** [comment]
Etapa de criação do diagrama, após o brainstorming:

![image](https://user-images.githubusercontent.com/68018675/232483169-0697e0d2-d4f3-424f-8e1b-ff400c6da6ce.png)
