### ISSUE TITLE
[FEAT] - Diagrama de Atividades

### ISSUE THREAD

**Issue by nszchagas** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#38]
# Feature

Criar o diagrama de atividades.

## Tarefas

- [x] Separar material de estudo 
- [x] Estudar o assunto 
- [x] Parear e fazer definições 
- [x] Elaborar artefato 

## Critérios de Aceitação
- [x] As ações devem ser representadas por verbo

[Link](https://lucid.app/users/registerOrLogin/free?showLogin=false&invitationId=inv_d1e066c4-020b-4dec-bdf5-61e04f740689&productOpt=chart&invitationType=documentAcceptance&returnUrlOverride=%2Flucidchart%2F30ee3921-4575-4438-a6bd-a934d2fbbc3e%2Fedit%3Fviewport_loc%3D-138%252C-393%252C2560%252C1168%252CM6oWhdaZwA6E%26invitationId%3Dinv_d1e066c4-020b-4dec-bdf5-61e04f740689) do diagrama.

**Comment by nszchagas** [comment]
Referências:
https://www.uml-diagrams.org/activity-diagrams.html 
Material da aula (slides sobre modelagem dinâmica)

**Comment by nszchagas** [comment]
@DaviSilva25 e @daves22, estava dando uma revisada no Richpicture e no Diagrama de Causa-Efeito pra ver quais fluxos podemos implementar na aplicação, e consegui visualizar duas atividades principais:

- Avaliação de Produto
- Visualização de Avaliações

## Avaliação de Produto

O usuário inicia essa atividade ao clicar em um botão "Avaliar Produto", em seguida:

1. Ele insere seus dados pessoais (email e nome **OU** efetua login)
2. Ele insere na avaliação (atividades paralelas):
    - Texto (obrigatório);
    - Modelo do produto (obrigatório?) [Ex: cor];
    - Fotos (0...n);
    - Data de Compra (0..1);
3. Ele envia a avaliação
4. Um email confirmando o recebimento da avaliação é enviado para o email do usuário
5. A avaliação é revisada pela administração do sistema
6. Um email confirmando se avaliação foi aprovada ou não (e o motivo) é enviado para o usuário

Nessa atividade vejo três raias no diagrama ("usuário", "administrador do sistema" e "sistema").

## Visualização de Avaliações

O usuário inicia essa atividade ao navegar até a seção de avaliações na página do produto, em seguida:

1. O usuário pode filtrar as avaliações:
    - Inserindo no filtro os campos opcionais: Contém Fotos?, Modelo do Produto e Data de Compra.
2. O usuário pode classificar as avaliações:
    - Para cada avaliação ele pode classificar como "relevante" ou "irrelevante".

O que acham?

**Comment by daves22** [comment]
Achei uma boa ideia acrescentar a parte de visualização de avaliações, o diagrama ficará mais completo! 
Um dos meus rascunhos ficou assim, sei que não esta certo mas é só para deixar registrado, fiz apenas com a parte de avaliar produto.

![rascunho-1-Diagrama-Dinamico](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/69313657/16e5b5bf-ba0e-495c-8a61-46c88678201c)

**Comment by DaviSilva25** [comment]
Esse foi o esboço que eu fiz e conversei com o Nicolas:
![esboçoDavi](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/79341819/358cd6e1-b5ea-432a-89ac-8ea4578c0a14)

E este foi o que a gente fez junto em sala para o segundo diagrama de visualização das avaliações:
![esboço](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/79341819/ae95ddee-8000-4912-a3ef-a3650e870337)

**Comment by DaviSilva25** [comment]
Eu fiz este aqui no LucidChart, validem pra mim por favor!

Aqui o link para o LucidChart, caso queiram fazer alguma alteração: 
https://lucid.app/lucidchart/4a45e1fa-3b0f-4076-be29-6d6fe899b386/edit?viewport_loc=-926%2C-108%2C3586%2C1770%2C0_0&invitationId=inv_56f1e38e-a02e-49d8-a5f6-0780dcc0e3c5

![DiagramaAtividadesVisualizar](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/79341819/d1ffe5a5-d336-4ee7-8b34-f5a776528fe3)

**Comment by daves22** [comment]
ficou ótimo @DaviSilva25 ! só arrumei um erro ortográfico e acho que está 10

![diagrama-de-avaliacao](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/69313657/a3471f9b-4668-4288-9c4d-26c4661b51b1)

**Comment by nszchagas** [comment]
Alterei o texto das ações para letra maíscula, coloquei nomes nas arestas de decisão de caminho e tirei as cores dos nós de inicio e final pra se adequar à notação UML. 

![Diagrama em branco](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/68018675/329497bb-5fb2-4e3b-a4a2-065496016ceb)
