### ISSUE TITLE
[FEAT] - Diagrama de Classe

### ISSUE THREAD

**Issue by zjosuez** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#39]
# Feature
Criar diagrama de classes 
## Tarefas

- [x] Separar material de estudo 
- [x] Estudar o assunto 
- [x] Desenhar um esboço inicial do diagrama de classes
- [x] Refinar o esboço inicial
- [ ] Enviar para revisão

[Link](https://lucid.app/lucidchart/4dd6a296-dbea-46b7-8bb7-b515fbc1fb05/edit?viewport_loc=-197%2C-21%2C2922%2C1261%2CHWEp-vi-RSFO&invitationId=inv_32177c76-50f9-40b1-95df-7711173e673f) para o diagrama

**Comment by zjosuez** [comment]
Criei essa issue específica do nosso artefato para ficar mais organizado

**Comment by MariaAbritta** [comment]
Criei os primeiros relacionamentos e deixei algumas dúvidas para podermos discutir.
Também comecei a fazer algumas Multiplicidades.

**Comment by lucasfs1007** [comment]
Dei uma analisada e fiz as seguintes alterações pensando da seguinte forma:

- como estamos tratando cliente e avaliação...Não somos obrigados necessariamente a avaliar, portanto podemos ter clientes sem avaliar (por isso iniciamos com 0) e como um único cliente pode fazer inúmeras avaliações dentro da plataforma (não se limitando a único produto) ele recebe "*". 
- O controle de estoque entra tanto na parte de troca e devolução de um produto como controle para saber se a reclamação corresponde ao produto em si ou uma amostra de um estoque em especifico. 
-

**Comment by lucasfs1007** [comment]
novas atualizações:

- alterei alguns nomes de classe que mantinham plural para estar no singular conforme sugerido pela professora.
- transferi os elementos mais essenciais da classe "monitoramento de estoque" vista que ela já está contida dentro da plataforma e o objetivo é deletar essa outra para mantermos apenas uma.
- a classe comprador faltava atributos e métodos em relação ao que ocorre no fluxo, alterei pois com a quantidade anterior, comprador seria uma subClasse e não uma classe de fato

**Comment by lucasfs1007** [comment]
![image](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/88278278/e2bd96a9-d4f1-4112-a8af-a87335f9c9c6)
a ordem que se da as multiplicidades para quem for revisar

**Comment by lucasfs1007** [comment]
file:///home/user/Imagens/questionamento1DiagramaDeClasses.png

**Comment by lucasfs1007** [comment]
![image](https://github.com/UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy/assets/88278278/9a96a96b-4439-45dd-85a6-ba49b7aab3fb)

**Comment by zjosuez** [comment]
Estou revisando o diagrama e trouxe um ponto para discurssão:
Não concordo com a relação de composição entre plataforma e produto. Isso implicaria que a "Plataforma" é um todo composto pelos "Produtos" que são vendidos nela. Entretanto, na realidade, a "Plataforma" não é formada pelos "Produtos" que vende, mas sim é uma entidade independente que oferece os "Produtos" para venda. 

Acredito que a relação entre eles seja associativa. Isso permite que cada "Produto" seja associado a uma única "Plataforma" onde é vendido, mas a "Plataforma" não é composta pelos "Produtos".

**Comment by lucasfs1007** [comment]
A branch "diagramaClasses"

**Comment by MariaAbritta** [comment]
> ![image](https://user-images.githubusercontent.com/88278278/237673711-e2bd96a9-d4f1-4112-a8af-a87335f9c9c6.png) a ordem que se da as multiplicidades para quem for revisar

A gente não está usando esse tipo de multiplicidade, se quiser usar, tem que escrever igual está na foto... acho que é isso que está te confundindo

**Comment by MariaAbritta** [comment]
> Estou revisando o diagrama e trouxe um ponto para discurssão: Não concordo com a relação de composição entre plataforma e produto. Isso implicaria que a "Plataforma" é um todo composto pelos "Produtos" que são vendidos nela. Entretanto, na realidade, a "Plataforma" não é formada pelos "Produtos" que vende, mas sim é uma entidade independente que oferece os "Produtos" para venda.
> 
> Acredito que a relação entre eles seja associativa. Isso permite que cada "Produto" seja associado a uma única "Plataforma" onde é vendido, mas a "Plataforma" não é composta pelos "Produtos". ![Captura de tela 2023-05-11 091022](https://user-images.githubusercontent.com/82157394/237682751-ade79159-7fd0-4aef-acaa-e812f4559df4.png)

Beleza... concordo! Pode fazer essa mudança, amigo!
