### ISSUE TITLE
Planos de Risco, Custo e Tempo

### ISSUE THREAD

**Issue by MariaAbritta** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#4]
Organização da parte dos Planos de Risco, Custo e Tempo, que devem ser entregues até o dia 19/04 pela manhã.

**Comment by MariaAbritta** [comment]
- [ ] Criar o esboço do nosso diagrama (14/04)
- [ ]  Adicionar os "Riscos" (16/04)
- [ ]  Adicionar as "Causas" (17/04)
- [ ]  Adicionar o "Tempo" (18/04)
- [ ]  Entrega do Diagrama completo, pela manhã (19/04)

**Comment by MariaAbritta** [comment]
Riscos
- [Processos de Gestão de Riscos (UFRN) ](https://www.ufrn.br/resources/documentos/planos/plano_de_Gestao_de_Riscos-PGR.pdf)
- [MANUAL Plano de Gestão de Riscos da UFRPE ](http://ww2.proplan.ufrpe.br/sites/ww2.proplan.ufrpe.br/files/MANUAL_GESTAO_DE_RISCOS_proposta_diagramacao.pdf)
- [Guia prático ](https://blog.softexpert.com/plano-de-riscos-completo-12-etapas/)

**Comment by guivilela7** [comment]
Tempo

- [Gerenciamento de projetos (Capítulo 6 Gerenciamento de Tempo)](https://books.google.com.br/books?hl=pt-BR&lr=&id=Wvdk7IaOC7wC&oi=fnd&pg=PA3&dq=plano+de+custo,+risco+e+tempo&ots=PfFsbU-8RO&sig=d1xKBWS0KVuq7Gws8Um77wvc0uk#v=onepage&q=plano%20de%20custo%2C%20risco%20e%20tempo&f=false)

**Comment by daves22** [comment]
Custo
- [Engenharia de Software e Sistemas da Informação](https://books.google.com.br/books?id=rtBvl_L-1mcC&printsec=frontcover&hl=pt-BR&source=gbs_ViewAPI&redir_esc=y#v=onepage&q&f=false)
- [Gestão de Custos](https://books.google.com.br/books?id=AB-HCgAAQBAJ&newbks=1&newbks_redir=0&printsec=frontcover&dq=plano+de+custo,+risco+e+tempo&hl=pt-BR&redir_esc=y#v=onepage&q&f=false)
- [Gerenciamento de custos em projetos](https://books.google.com.br/books?id=EX9ZEAAAQBAJ&printsec=frontcover&dq=gerenciamento+de+custo&hl=pt-BR&newbks=1&newbks_redir=0&sa=X&redir_esc=y#v=onepage&q=gerenciamento%20de%20custo&f=false)
