### ISSUE TITLE
[PADRÃO DE PROJETO] Comunicação do Front-End

### ISSUE THREAD

**Issue by MariaAbritta** [UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy#60]
### Contexto
Comunicação do frontend (API) (englobando os serviços de CRUD, tratamento dos dados pra exibir no front e etc)

**Tarefas**
- Padrão GoF a ser utilizado - Observer (Observador)
- [x] Implementar o Padrão GoF no cenário de avaliações/feedbacks (Membro: @MariaAbritta)

- Padrão GRASP - Controlador (Controller)
- [x] Trazer o Padrão GRASP: Controlador (Controller) - O Controlador receber as solicitações do frontend (API) e interpreta as ações do usuário. (Membro: Josué Teixeira)
- [x] Trazer o Padrão GRASP: Controlador (Controller) -  O Controlador poder chamar os métodos apropriados do modelo (ou serviços relacionados ao modelo) para manipular os dados do sistema. (Membro: @MariaAbritta)
- [ ] Trazer o Padrão GRASP: Controlador (Controller) -  O Controlador ser responsável por atualizar a visão correspondente à solicitação recebida. (Membro: @MariaAbritta)
- [ ] Trazer o Padrão GRASP: Controlador (Controller) -  O Controlador poder executar validações de entrada, aplicar regras de negócios e garantir que as operações sejam executadas corretamente e dentro das restrições definidas. (Membro: @MariaAbritta)
- [x] #66

- Padrão de Arquitetura - MVC (Model-View-Controller)
- [x] Trazer o Padrão de Arquitetura - MVC (Model-View-Controller) - Modelo (Model) do nosso projeto (Membro: @MariaAbritta)
- [x] Trazer o Padrão de Arquitetura - MVC (Model-View-Controller) - Visão (View) do nosso projeto (Membro: @MariaAbritta)
- [ ] Trazer o Padrão de Arquitetura - MVC (Model-View-Controller) - Controlador (Controller) do nosso projeto (Membro: @pedroblome)

**Comment by MariaAbritta** [comment]
Criei e finalizei a parte de Padrão GOF: Observer (Observador), criando pseudocódigos relacionadas a Avaliações/Feedbacks

**Comment by MariaAbritta** [comment]
Atualizei o pseudocódigo do @zjosuez para a linguagem Java, definida pela equipe anteriormente

**Comment by MariaAbritta** [comment]
Criei e finalizei a parte de - Trazer o Padrão GRASP: Controlador (Controller) - O Controlador poder chamar os métodos apropriados do modelo (ou serviços relacionados ao modelo) para manipular os dados do sistema
- [ ] Revisar

**Comment by zjosuez** [comment]
Atualizei o [Diagrama de classes](https://lucid.app/lucidchart/4dd6a296-dbea-46b7-8bb7-b515fbc1fb05/edit?invitationId=inv_32177c76-50f9-40b1-95df-7711173e673f&page=HWEp-vi-RSFO#) com o padrão 'Observer' englobando todos os aspectos desse desing pattern.

**Comment by zjosuez** [comment]
Também adicionei um arquivo com uma breve explicação sobre o funcionamento do padrão "Observer" no [Diagrama de classes](https://lucid.app/lucidchart/4dd6a296-dbea-46b7-8bb7-b515fbc1fb05/edit?invitationId=inv_32177c76-50f9-40b1-95df-7711173e673f&page=HWEp-vi-RSFO#).

**Comment by DaviSilva25** [comment]
Adicionei no pages a demonstração no terminal que eu e o Guilherme fizemos a partir do pseud-código do Josué.
